name: Deploy/gh-pages

on: 
  push:
    branches: [main]
jobs: 
  build:
    name: Publish build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 20.8.1
        uses: actions/setup-node@v2
        with:
          node-version: '20.8.1'

      - name: Install independecies
        run: npm install

      - run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
      